---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: secure-gitops-pipeline-dev
spec:
  encryptedData:
    API_KEY: AgBB16houdnnaWaFxlkj7VxySkjQCivYZN2wutCjs6gNvAIbArv2Z4NN6xzsY2d3QnOprZB48wwKTHe8VZkRyx1H+sZRDH/MtTB0iWaUehQ9jUFsAgLa0ooVEyu7XCTvUaIkrs+WYP7wKcJ07Ct/vVk0p4KO1wLr1dKU+nPL0JvtIMkdeNGJw/2FbErAzA5xDnYwuDMkvncHLx1OYO/iN2vY6p+AXJqnN/Wg6OUj2YNJXl7tBv4/k8FFjsYZp3CZn5T7Lj9/+4EQBAI2jFWiBOycVguc14eKNwfZfSC0Y+4tKtJIDgN/vGsih06QF4u1dWz0fVbUchQM5seOvJbPz5OXswxjqutrTWVVUIxTPUtwPyd6sUTGNtxYewVyg7rMZtylW8gUqoPPtgMbDSzXGz/qDyGoH3S0bht7MbIKkvfesm2ln1WU0+K6l4k7iP4Oo6+6bvSmCN+UORDgcnyCULiUm5Q5tZENNkQKAxtWD4A73DvgWOYa3Qe7gSH2Ql1pExL6BNgTqx7XkxGQSgtHZZ01j7DvuXCugvqS5J0byPyosEn11h/fqMTg05yU4QGxtsi7Ah/kUjTNvVH9Tf6dztD4E5izOAnoLV3SBiGk4YYNvuTL2w59ukAS7ZO36u7QpnPMOHr+qiRVJSauCvkOBN5P0GEu1X17ArJWnOkb3IFSWhqteBZCGe+i3yTm/eSnQizckosxRBm6Gkc8nBENpz4WZXfuV1aT2Q==
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: secure-gitops-pipeline-dev
