---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: secure-gitops-pipeline-prod
spec:
  encryptedData:
    API_KEY: AgAMYs/DRVSoVXZfXwqYgvgfPBLGklcSmfFWUa8Pgfc1R9KeNrymcMV9YaeHoYHnS02lmrwUm2n750dVD+0vfv3/eDJKx/2wSa4nqJMdrmYhHM0VXdLTp1agAHaUPVFzuRy2OK3gWXM1wPKq0GNjD44QBlYngfcDXImZdRu3pirgBS9cBhggglYkRTz7N8UfCn12P4H8b49fZQp7BPVL/kiXeFqX9hJXXDmktXRxD2ry/0+P5MdPHmJvQMC6CwB7z56TgJbVgp+A4nz7cC/7IJpf1maDPaO7vzISeT/KsKXYAfCR9ns0yowCKbbz4i95QTaUK1vFBIW013dbQQUnCuBU2YeOqkdAjML1BMGSpikw4Pi55ebrc8ZaNCfreNoCY30REav6HFOQVS/Ux2GSv2TehSJgslpsCoTk2aYM9cMioPSuOf36BAG264LGRiLkCyKgL+tli85CPOspMW+uqEkSwGYPdfXRGB18bq8w20CFp4VG7l2hWU5PeW1Va16Qu18RkjFF0UHLecfeIsF6CqhNZpfSILGcO5y7VjDx1vNd/jE6igpzvlEgJu3dtrgeH80RmPk2pUe5l7uQkxHsrHbA+JonQfbI0hnhMhTjrHSwh2alfsOPhJcw5D/0PAeuose1syHpgtrwSOtG8ft4aAFkiFLCYxE8er2jDCKfWpLd+umo3mfIVD8dIwu5Q0nj6ABfcmX4ho1Mz5LUbaH+Yv2Bkl/Kvwd8a3/nsUx5
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: secure-gitops-pipeline-prod
