apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: myapp
    newName: ghcr.io/khaoula-dr/secure-gitops-pipeline
    newTag: latest   # écrasé par `kustomize edit set image` dans les overlays
