apiVersion: v1
kind: Service
metadata:
  name: secure-gitops-pipeline
  labels:
    app: secure-gitops-pipeline
spec:
  type: ClusterIP
  selector:
    app: secure-gitops-pipeline
  ports:
    - name: http
      port: 80
      targetPort: http
